ocr_data_public:
  data_structure: one_by_one.standard_ocr_data.data_structure.StandardOcrData
  processor_class: one_by_one.standard_ocr_data.processor.StandardOcrDataProcessor
  image_dir: C:\Users\wjh\Downloads\OCR데이터(공공)\Sample\01.원천데이터
  label_dir: C:\Users\wjh\Downloads\OCR데이터(공공)\Sample\02.라벨링데이터
  save_dir: C:\Users\wjh\Desktop\dataset\ocr_data_public

ocr_data_education:
  data_structure: one_by_one.standard_ocr_data.data_structure.StandardOcrData
  processor_class: one_by_one.standard_ocr_data.processor.StandardOcrDataProcessor
  image_dir: C:\Users\wjh\Downloads\OCR데이터(교육)\Sample\01.원천데이터
  label_dir: C:\Users\wjh\Downloads\OCR데이터(교육)\Sample\02.라벨링데이터
  save_dir: C:\Users\wjh\Desktop\dataset\ocr_data_education

ocr_data_finance:
  data_structure: one_by_one.standard_ocr_data.data_structure.StandardOcrData
  processor_class: one_by_one.standard_ocr_data.processor.StandardOcrDataProcessor
  image_dir: C:\Users\wjh\Downloads\OCR데이터(금융및물류)\Sample\01.원천데이터
  label_dir: C:\Users\wjh\Downloads\OCR데이터(금융및물류)\Sample\02.라벨링데이터
  save_dir: C:\Users\wjh\Desktop\dataset\ocr_data_finance

various_forms_hangul:
  data_structure: one_by_one.various_forms_of_hangul.data_structure.VariousFormsOfHangulData
  processor_class: one_by_one.various_forms_of_hangul.processor.VariousFormsOfHangulProcessor
  image_dir: C:\Users\wjh\Downloads\다양한형태의한글문자\원천데이터
  label_dir: C:\Users\wjh\Downloads\다양한형태의한글문자\라벨링데이터
  save_dir: C:\Users\wjh\Desktop\dataset\various_forms_hangul

kor_pub_doc:
  data_structure: one_by_one.kor_pub_doc.data_structure.KorPubDocData
  processor_class: one_by_one.kor_pub_doc.processor.KorPubDocDataProcessor
  image_dir: C:\Users\wjh\Downloads\공공행정문서\원천데이터
  label_dir: C:\Users\wjh\Downloads\공공행정문서\라벨링데이터
  save_dir: C:\Users\wjh\Desktop\dataset\kor_pub_doc

finance_ocr:
  data_structure: one_by_one.finance_ocr.data_structure.FinanceOcrData
  processor_class: one_by_one.finance_ocr.processor.FinanceOcrProcessor
  image_dir: C:\Users\wjh\Downloads\금융업특화OCR\원천데이터
  label_dir: C:\Users\wjh\Downloads\금융업특화OCR\라벨링데이터
  save_dir: C:\Users\wjh\Desktop\dataset\finance_ocr

large_handwriting:
  data_structure: one_by_one.large_handwriting.data_structure.LargeHandwritingData
  processor_class: one_by_one.large_handwriting.processor.LargeHandwritingDataProcessor
  image_dir: C:\Users\wjh\Downloads\대용량손글씨\원천데이터
  label_dir: C:\Users\wjh\Downloads\대용량손글씨\라벨링데이터
  save_dir: C:\Users\wjh\Desktop\dataset\large_handwriting
