ocr_data_public:
  data_structure: rec.one_by_one.ocr_data_public.data_structure.OcrDataPublic
  processor_class: rec.one_by_one.ocr_data_public.processor.StandardOcrDataProcessor
  image_dir:
  label_dir:
  save_dir: /data/results/ocr_data_public

ocr_data_education:
  data_structure: rec.one_by_one.ocr_data_education.data_structure.OcrDataEducation
  processor_class: rec.one_by_one.ocr_data_education.processor.StandardOcrDataProcessor
  image_dir:
  label_dir:
  save_dir: /data/results/ocr_data_education

ocr_data_finance:
  data_structure: rec.one_by_one.ocr_data_finance.data_structure.OcrDataFinance
  processor_class: rec.one_by_one.ocr_data_finance.processor.StandardOcrDataProcessor
  image_dir:
  label_dir:
  save_dir: /data/results/ocr_data_finance

various_forms_hangul:
  data_structure: rec.one_by_one.various_forms_of_hangul.data_structure.VariousFormsOfHangulData
  processor_class: rec.one_by_one.various_forms_of_hangul.processor.VariousFormsOfHangulProcessor
  image_dir: /data/031.다양한_형태의_한글_문자_이미지_인식_데이터/01.데이터/1.Training
  label_dir: /data/031.다양한_형태의_한글_문자_이미지_인식_데이터/01.데이터/1.Training
  save_dir: /data/results/various_forms_of_hangul

kor_pub_doc:
  data_structure: rec.one_by_one.kor_pub_doc.data_structure.KorPubDocData
  processor_class: rec.one_by_one.kor_pub_doc.processor.KorPubDocDataProcessor
  image_dir: mnt/data1/ai/dataset/032.공공행정문서_OCR/01.데이터/01.Training
  label_dir: mnt/data1/ai/dataset/032.공공행정문서_OCR/01.데이터/01.Training
  save_dir: /data/results/kor_pub_doc

finance_ocr:
  data_structure: rec.one_by_one.finance_ocr.data_structure.FinanceOcrData
  processor_class: rec.one_by_one.finance_ocr.processor.FinanceOcrProcessor
  image_dir:
  label_dir:
  save_dir: /data/results/finance_ocr

large_handwriting:
  data_structure: rec.one_by_one.large_handwriting.data_structure.LargeHandwritingData
  processor_class: rec.one_by_one.large_handwriting.processor.LargeHandwritingDataProcessor
  image_dir:
  label_dir:
  save_dir: /data/results/large_handwriting
